### PR TITLE
Adding TrueCharts

### PR DESCRIPTION
**Pull request by Ornias1993**
TrueCharts is actively porting the current K8S-at-Home library to TrueNAS SCALE, which itself is based on k3s.

Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

### CODE REVIEW

**Comment by carpenike** [comment]
Hey @Ornias1993, appreciate the PR!

Are you working with IXSystems directly or is this a community effort? Looks like you're duplicating some of the effort on your fork. Any reason to not integrate directly with this project?

**Comment by Ornias1993** [comment]
@carpenike It's a community effort, I'm not (directly) associated with IX systems. Both me and the primary person responsible for their own "Official" Apps, also have relevant differences in design-philosophy.

If you take a carefull look at TrueNAS SCALE applications you would notice it's not compatible with default Helm Charts.
It (sadly enough) requires additional files, custom way of referencing certain things like storage and different folder structure.

I'm also not limiting myself to k8s-at-home charts, as you can see in both the master and dev branch.

**Comment by carpenike** [comment]
Yup understood. 

How about we create a separate section in this page titled `Helm Chart Repositories` where we link to your repo?

Would you also mind adding recognition with linkage back to either the k8s-at-home charts repo or https://k8s-at-home.com where appropriate?

**Comment by onedr0p** [comment]
@Ornias1993 I have included this in an update here https://github.com/k8s-at-home/awesome-home-kubernetes

**Comment by Ornias1993** [comment]
@onedr0p If I would mind about such small things, I should definately stay away from the Internet ;-)
Thanks for the effort! :)

**Pull request closed without merging**
