### PR TITLE
Script to automatically update search badges based on the repo list

### PR DESCRIPTION
**Pull request by lanquarden**
A script to automatically update the search badges based on repo list, as @bjw-s suggested, meant to be run by a github action upon opening a PR.

### CODE REVIEW

**Comment by bjw-s** [comment]
Thanks for adding this! I'll try to add a GH workflow to this branch somewhere tomorrow 👍

**Comment by onedr0p** [comment]
Script might need to be updated to work with the new formatting I added. Sorry :)

**Comment by bjw-s** [comment]
I actually forgot about this PR and that I was supposed to whip up a workflow 😊

**Comment by bjw-s** [comment]
@onedr0p I've updated the PR with an updated script and a GH workflow, can you take a look?

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
Gracias!

**Pull request merged**
