### PR TITLE
Sort by gitops

### LINKED ISSUE #46: Re-organize repos by GitOps used (eg. Argo vs Flux)
# Details

**Describe the solution you'd like:** I would like a simple way to search only on argo or Flux repos

**Anything else you would like to add:** It's currently rather hard to try to understand how to do things on Flux when looking at an Argo repo by mistake.

### PR DESCRIPTION
**Pull request by samip5**
**Description of the change**

I changed the way the data is processed and sorting by gitops used.

**Benefits**

Ability to search only for Argo / Flux related repos for examples.

**Possible drawbacks**

Not very intuitive code for non-python savys.

**Applicable issues**

- fixes #46

### CODE REVIEW

**Comment by bjw-s** [comment]
Thanks for making this PR! 

I like the idea, but I'm not really sure of this implementation tbh. (Also the changed indentation makes it harder to review, but that's a bit of a technicality)

I would add an optional field per repo where the gitops type can be specified. Then we can add search buttons per type, alongside the `all` search.

**Comment by samip5** [comment]
> I like the idea, but I'm not really sure of this implementation tbh. (Also the changed indentation makes it harder to review, but that's a bit of a technicality)

What about the indention change makes it hard to review? It's in a separate commit for that specific reason and easier to revert if needed. The code was not following PEP8 (https://www.python.org/dev/peps/pep-0008/, https://realpython.com/python-pep8/) previously, now it is.

What do you propose in terms of how it's implemented? I personally dislike the approach where it's an optional field.

**Comment by bjw-s** [comment]
> What about the indention change makes it hard to review? It's in a separate commit for that specific reason and easier to revert if needed. The code was not following PEP8 (https://www.python.org/dev/peps/pep-0008/, https://realpython.com/python-pep8/) previously, now it is.

The process of reviewing a Github PR. It now shows all the files as changed, and there is a mix of functional and layout changes. I'm all for making the script adhere to PEP8 conventions, but would want to see a separate PR for that.

> What do you propose in terms of how it's implemented? 

I kind of proposed that already in my initial comment.

> I personally dislike the approach where it's an optional field.

One reason is that not every repo in here is required to be a gitops repo. In your current proposal we would end up with `["argocd", "flux", "other"]` dicts, whereas the type of gitops tool used (if any) is basically just metadata for the repository and should be treated as such.

**Comment by bjw-s** [comment]
Superseded by #59

**Pull request closed without merging**
